# Funding links shown by GitHub in the "Sponsor"/"Support" UI on the repo page.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - https://buymeacoffee.com/bartg
